<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Tchat box</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" media="screen" href="css/main.css" />
    
</head>
<body>
    <form class="form-access">
        <h1><i class="fas fa-lock"></i> Connexion</h1>
        <p id="fail" class="hide"></p>    
        <input type="text" class="inputtext" id="inputLogin" name="inputLogin" placeholder="Login" required autofocus>

        <input type="password" class="inputtext" id="inputPassword" name="inputPassword" placeholder="Password" required>

        <button type="submit" id="connect">Connexion</button>
        <a href="inscription.php" id="inscription">Inscription</a>
    </form>
    <script src="js/jquery-3.4.0.min.js"></script>
    <script src="js/main.js"></script>
</body>
</html>