<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Tchat box</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" media="screen" href="css/main.css" />
    
</head>
<body>
    
    <section class="chtat">
        <div id="messages">
                    <!-- les messages du tchat -->
                <?php for($i = 0; $i<count($tab); $i++): ?>
                <?php if($tab[$i]['Id'] == $_GET['id_User']): ?>
                    <p class="textgauche"><?= $tab[$i]['Dialogue'] ?></p>
                    <p class="gauche"><em>Ecrit par</em> <strong><?= $tab[$i]['Pseudo'] ?></strong><em> le <?= $tab[$i]['Date'] ?></em></p>
                    <input class="idMessage" name="idMessage" type="hidden" value="<?= $tab[$i]['mId'] ?>">
                <?php else: ?>
                
                    <p class="textdroite"><?= $tab[$i]['Dialogue'] ?></p>
                    <p class="droite"><em>Ecrit par</em> <strong><?= $tab[$i]['Pseudo'] ?></strong><em> le <?= $tab[$i]['Date'] ?></em></p>
                    <input class="idMessage" name="idMessage" type="hidden" value="<?= $tab[$i]['mId'] ?>">
                
                <?php endif; ?>
                <?php endfor; ?>
        </div>

        <form method="POST" class="formMessage" action="traitement.php">
            <textarea row="5" class="textMessage" cols="100" name="message" id="message" placeholder="tapez votre message ici..."></textarea><br />
            <input type="submit" class="envoimessage" name="submit" value="Envoyez votre message !" id="envoi" />
        </form>
    </section>
    <section class="doc">
        <div class="participants">
            <h2>liste des participants</h2>
        </div>
        <article id="salons">
            <div class="discussions">
                <h2>Salons auxquels vous participez</h2>
            </div>
            <a id="newDiscussion" href="#">Créer nouvelle discussion</a>
        </article>
    </section>
    <script src="js/jquery-3.4.0.min.js"></script>
    
    <script src="js/creation.js"></script>
    <script src="js/main.js"></script>
</body>
</html>