<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Tchat box</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" media="screen" href="css/main.css" />
    
</head>
<body>
    <div id="messages">
                <!-- les messages du tchat -->
            <?php for($i = 0; $i<count($tab); $i++): ?>
            <?php if($tab[$i]['Id'] == $_GET['id_User']): ?>
                <p class="textgauche"><?= $tab[$i]['Dialogue'] ?></p>
                <p class="gauche">Ecrit par <?= $tab[$i]['Pseudo'] ?> le <?= $tab[$i]['Date'] ?></p>
                <input class="idMessage" name="idMessage" type="hidden" value="<?= $tab[$i]['mId'] ?>">
            <?php else: ?>
            
                <p class="textdroite"><?= $tab[$i]['Dialogue'] ?></p>
                <p class="droite">Ecrit par <?= $tab[$i]['Pseudo'] ?> le <?= $tab[$i]['Date'] ?></p>
                <input class="idMessage" name="idMessage" type="hidden" value="<?= $tab[$i]['mId'] ?>">
            
            <?php endif; ?>
            <?php endfor; ?>
    </div>

    <form method="POST" action="traitement.php">
        Message : <textarea row="5" cols="100" name="message" id="message"></textarea><br />
        <input type="submit" name="submit" value="Envoyez votre message !" id="envoi" />
    </form>
    <script src="js/jquery-3.4.0.min.js"></script>
    <script src="js/main.js"></script>
</body>
</html>